code --install-extension adpyke.codesnap
code --install-extension Anan.jetbrains-darcula-theme
code --install-extension cschlosser.doxdocgen
code --install-extension eamodio.gitlens
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension fisheva.eva-theme
code --install-extension llvm-vs-code-extensions.vscode-clangd
code --install-extension maximetinu.identical-sublime-monokai-csharp-theme-colorizer
code --install-extension mhutchie.git-graph
code --install-extension MS-CEINTL.vscode-language-pack-zh-hans
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension mskelton.one-dark-theme
code --install-extension mutantdino.resourcemonitor
code --install-extension njpwerner.autodocstring
code --install-extension rust-lang.rust
code --install-extension twxs.cmake
code --install-extension vscode-icons-team.vscode-icons
